# ./swan/common/constant.py

SWAN_API = "https://swanhub-cali.swanchain.io"

# Swan API
APIKEY_LOGIN = "/login_by_api_key"
DEPLOY_TASK = "/v1/space_deployment"
DEPLOYMENT_INFO = "/v1/space_deployment/<string:task_uuid>"
GET_CP_CONFIG = "/cp/machines"

API_TOKEN = "/api_token"
DELETE_API_TOKEN = "/api_token/delete"
VALIDATE_API_TOKEN = "/api_token/validate"
ADDRESS_FROM_TOKEN = "/address_from_token"
PUBLIC_ADDRESS = "/public_address"
COMPUTE_PROVIDER = "/cp"
AUTHENTICATE_PROVIDER = "/cp/<string:apikey>"
CONNECT_CP = "/cp/connect"
UPDATE_CP = "/cp/update"
DELETE_CP = "/cp/delete"
PROVIDER_DASHBOARD = "/cp/dashboard"
UPDATE_CP_RESOURCES = "/cp/summary"
UPDATE_CP_STATUS = "/cp/heartbeat"
CHECK_ACTIVE_CP = "/cp/active"
FILTER_CP_BY_NAME = "/cp/filter/<string:serach_string>"
GET_CP_DETAILS = "/cp/details/<string:node_id>"
UPDATE_JOB_STATUS = "/job/status"
SPACE_CP_DETAIL = "/cp/<string:node_id>/<string:space_uuid>"
COLLATERAL_BALANCE = "/cp/collateral/<string:cp_address>"
EXTEND_JOBS = "/cp/extend_task"
CHECK_FROZEN_COLLATERAL = "/check_holding_collateral/<string:wallet_address>"
CP_DISTRIBUTION = "/cp_distribution"
AVAILABLE_CPS = "cp_avilable"
CP_LIST = "/cp_list"
CP_DETAIL = "/cp_detail/<string:cp_id>"
CONFIG_ORDER = "/v1/active_order/<string:task_uuid"
HOST_INFO = "/host/info"
AUCTION_INFO = "/auction/info"
STATS = "/stats/general"
TASK_BIDDING = "/task/bidding"
TASKS = "/tasks"
JOB_UUID = "/tasks/job_uuid/<string:task_uuid>"
DEPLOY_STATUS = "/tasks/deploy_space/"
REFUNDABLE_STATUS = "check_refundable/<string:task_uuid>"
USER_PROVIDER_PAYMENTS = "/user/provider/payments"
PROVIDER_PAYMENTS = "/provider/payments"
WALLET_ADDRESS = "/jwt_info"
VALIDATE_PAYMENT = "/payment_validate"
CLAIM_REVIEW = "/claim_review"
TERMINATE_TASK = "/terminate_task"

# API Syntax
REST_API_VERSION = "v1"
GET = "GET"
PUT = "PUT"
POST = "POST"
DELETE = "DELETE"

# Contract
PAYMENT_CONTRACT_ABI = "PaymentContract.json"
SWAN_TOKEN_ABI = "SwanToken.json"

# Other
CONTRACT_TIMEOUT = 300
STORAGE_LAGRANGE: str = "lagrange"
ORCHESTRATOR_API = "orchestrator-api.swanchain.io"
MAX_DURATION = 1209600

# MCS API
MCS_POLYGON_MAIN_API = "https://api.multichain.storage"
MCS_POLYGON_MUMBAI_API = "https://calibration-mcs-api.filswan.com"
MCS_BSC_API = 'https://calibration-mcs-bsc.filswan.com'
FIL_PRICE_API = "https://api.filswan.com/stats/storage"
MCS_PARAMS = "/api/v1/common/system/params"
PRICE_RATE = "/api/v1/billing/price/filecoin"
PAYMENT_INFO = "/api/v1/billing/deal/lockpayment/info"
TASKS_DEALS = "/api/v1/storage/tasks/deals"
MINT_INFO = "/api/v1/storage/mint/info"
UPLOAD_FILE = "/api/v1/storage/ipfs/upload"
DEAL_DETAIL = "/api/v1/storage/deal/detail/"
USER_REGISTER = "/api/v1/user/register"
USER_LOGIN = "/api/v1/user/login_by_metamask_signature"
GENERATE_APIKEY = "/api/v1/user/generate_api_key"
APIKEY_LOGIN = "/api/v2/user/login_by_api_key"
COLLECTIONS = "/api/v1/storage/mint/nft_collections"
COLLECTION = "/api/v1/storage/mint/nft_collection"
CREATE_BUCKET = "/api/v2/bucket/create"
BUCKET_LIST = "/api/v2/bucket/get_bucket_list"
DELETE_BUCKET = "/api/v2/bucket/delete"
FILE_INFO = "/api/v2/oss_file/get_file_info"
DELETE_FILE = "/api/v2/oss_file/delete"
CREATE_FOLDER = "/api/v2/oss_file/create_folder"
CHECK_UPLOAD = "/api/v2/oss_file/check"
UPLOAD_CHUNK = "/api/v2/oss_file/upload"
MERGE_FILE = "/api/v2/oss_file/merge"
FILE_LIST = "/api/v2/oss_file/get_file_list"
GET_FILE = "/api/v2/oss_file/get_file_by_object_name"
GET_GATEWAY = "/api/v2/gateway/get_gateway"
PIN_IPFS = "/api/v2/oss_file/pin_files_to_ipfs"