""" Constants used in the project """

SWAN_API = "https://swanhub-cali.swanchain.io"
AUCTION_API = "http://172.16.200.12:5003"
GET = "GET"
POST = "POST"
PUT = "PUT"
DELETE = "DELETE"
# auction api
CELERY = "/celery/task/status/"
JOBS = "/lagrange/jobs"
PROCESSING_TASKS = "/api/tasks/processing"
DASHBOARD = "/"
APIKEY_LOGIN = "/login_by_api_key"
TASK_BIDDING = "/task/bidding"
